import dynamic from 'next/dynamic';
import Head from 'next/head';
import { AppPage } from '../utils/next';
import { internalFunc } from 'internal';

// @ts-ignore
const SharedComponent = dynamic(() => import('shared/shared-component'), {
  ssr: true,
});

const Home: AppPage = function () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <p>Main content</p>

          <SharedComponent />

          <p>{internalFunc()}</p>
        </div>
      </main>
    </>
  );
};

export default Home;
